name: Deploy Documentation
on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt install libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Rust Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --no-deps
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          commit_message: "🚀 ${{ github.event.head_commit.message }}"
